config/routes.rb
Rails.application.routes.draw do
  resources :regions
  resources :countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:code, :name)
    end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name, :description, :country_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.code %></td>
        <td><%= country.name %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @country.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeRegions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/regions/_form.html.erb
<%= form_with(model: region, local: true) do |form| %>
  <% if region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.text_field :country_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Regions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= region.description %></td>
        <td><%= region.country %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Region', new_region_path %>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @region.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @region.description %>
</p>

<p>
  <strong>Country:</strong>
  <%= @region.country %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>